services:

    payum.payrexx_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Instride\Payum\Payrexx\PayumPayrexxGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: payrexx }

    Instride\Bundle\PimcorePayumPayrexxBundle\Form\Type\PayrexxType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: payrexx }
            - { name: form.type }
